-- Aurora Wave — a 5-stop gradient generated by walking around the color
-- wheel (HSL hue rotation) instead of picking hex values by hand, for a
-- shifting northern-lights palette on the Live Spectrum bars.

local function hsl_to_hex(h, s, l)
  -- h: 0-360, s/l: 0-1
  local c = (1 - math.abs(2 * l - 1)) * s
  local x = c * (1 - math.abs((h / 60) % 2 - 1))
  local m = l - c / 2
  local r, g, b = 0, 0, 0
  if h < 60 then r, g, b = c, x, 0
  elseif h < 120 then r, g, b = x, c, 0
  elseif h < 180 then r, g, b = 0, c, x
  elseif h < 240 then r, g, b = 0, x, c
  elseif h < 300 then r, g, b = x, 0, c
  else r, g, b = c, 0, x end
  local function to255(v) return math.floor((v + m) * 255 + 0.5) end
  return string.format("#%02X%02X%02X", to255(r), to255(g), to255(b))
end

local colors = {}
local stops = 5
local start_hue = 160   -- teal
local hue_span = 140    -- sweeps up through blue into violet
for i = 1, stops do
  local hue = start_hue + hue_span * (i - 1) / (stops - 1)
  colors[i] = hsl_to_hex(hue % 360, 0.75, 0.55)
end

visualizer = {
  colors = colors,
  sensitivity = 1.15,
  bar_corner_radius = 3,
  bar_spacing = 3,
  mirrored = false,
}
