package com.stash.opusplayer.service

object EnhancedAudioCommands {
    // Enhanced Equalizer Commands
    const val COMMAND_TOGGLE_EQUALIZER = "SET_EQ_ENABLED"
    const val COMMAND_SET_PRESET = "SET_EQ_PRESET"
    const val COMMAND_SET_BAND_LEVEL = "SET_EQ_BAND"
    const val COMMAND_SET_BASS_BOOST = "SET_BASS_BOOST"
    const val COMMAND_SET_VIRTUALIZER = "SET_VIRTUALIZER"
    
    // Professional Audio Processor Commands
    const val COMMAND_TOGGLE_PROFESSIONAL_PROCESSOR = "TOGGLE_PROFESSIONAL_PROCESSOR"
    const val COMMAND_SET_COMPRESSION_ENABLED = "SET_COMPRESSION_ENABLED"
    const val COMMAND_SET_COMPRESSION_THRESHOLD = "SET_COMPRESSION_THRESHOLD"
    const val COMMAND_SET_COMPRESSION_RATIO = "SET_COMPRESSION_RATIO"
    const val COMMAND_SET_COMPRESSION_ATTACK = "SET_COMPRESSION_ATTACK"
    const val COMMAND_SET_COMPRESSION_RELEASE = "SET_COMPRESSION_RELEASE"
    const val COMMAND_SET_STEREO_WIDTH = "SET_STEREO_WIDTH"
    const val COMMAND_SET_AUTO_GAIN_ENABLED = "SET_AUTO_GAIN_ENABLED"
    const val COMMAND_SET_TARGET_LUFS = "SET_TARGET_LUFS"
    const val COMMAND_SET_CROSSFEED_ENABLED = "SET_CROSSFEED_ENABLED"
    const val COMMAND_SET_TUBE_WARMTH = "SET_TUBE_WARMTH"
    const val COMMAND_LOAD_AUDIO_PROFILE = "LOAD_AUDIO_PROFILE"
    
    // Spectrum Analyzer Commands
    const val COMMAND_TOGGLE_SPECTRUM_ANALYZER = "TOGGLE_SPECTRUM_ANALYZER"
    
    // Enhanced Audio Manager Commands
    const val COMMAND_SET_ENHANCED_AUDIO_ENABLED = "SET_ENHANCED_AUDIO_ENABLED"
    const val COMMAND_SET_AUDIO_PROFILE = "SET_AUDIO_PROFILE"
    const val COMMAND_SET_AUTO_PROFILE_SWITCHING = "SET_AUTO_PROFILE_SWITCHING"
}