#!/usr/bin/env bash
set -euo pipefail

# Build StashOpusPlayer with caches and outputs on the Steam_Recordings external drive.
# Usage:
#   scripts/build_to_steam_recordings.sh [gradle_task...]
# Examples:
#   scripts/build_to_steam_recordings.sh assembleDebug
#   scripts/build_to_steam_recordings.sh assembleRelease

EXT="/run/media/liveuser/Steam_Recordings"
[ -d "$EXT" ] || { echo "External drive not mounted at $EXT" >&2; exit 1; }

# Gradle cache on the external drive
export GRADLE_USER_HOME="$EXT/.gradle"

BASE_BUILD_DIR="$EXT/StashOpusPlayer-build"
INIT_DIR="$BASE_BUILD_DIR/config"
INIT_FILE="$INIT_DIR/init.gradle"

mkdir -p "$INIT_DIR" "$GRADLE_USER_HOME" "$BASE_BUILD_DIR"

# Create init.gradle if missing (kept outside project sources)
if [ ! -f "$INIT_FILE" ]; then
  cat > "$INIT_FILE" <<'EOF'
// Gradle init script to redirect build outputs to external drive
// Generated by build_to_steam_recordings.sh. No changes to project sources are made.

def baseBuildDir = new File('/run/media/liveuser/Steam_Recordings/StashOpusPlayer-build')
if (!baseBuildDir.exists()) { baseBuildDir.mkdirs() }

gradle.settingsEvaluated { settings ->
    settings.gradle.beforeProject { Project p ->
        String folderName = (p == settings.rootProject) ? 'root' : p.name
        File outDir = new File(baseBuildDir, folderName)
        p.buildDir = outDir
    }
}
EOF
fi

cd "$(dirname "$0")/.."
TASKS=("${@:-assembleDebug}")

# Run gradle with init script and caches on external drive
exec ./gradlew --no-daemon --stacktrace --warning-mode=all \
  -I "$INIT_FILE" \
  "${TASKS[@]}"
